app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls import include, path


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('interview/', include('interview.urls')),
    path('', include('viz.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

base/urls.py
from django.urls import include, path

app_name = 'base'
urlpatterns = [
]

viz/urls.py
from django.urls import include, path

from .views import detail, list, compare, json_export

app_name = 'viz'
urlpatterns = [
    path('', list, name='list'),
    path('<int:interview_id>', detail, name='detail'),
    path('<int:interview_id>/json', json_export, name='json'),
    path('compare', compare, name='compare'),
]

base/models.py
from django.db import models

from django.contrib.auth import get_user_model


class Candidate(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Position(models.Model):
    OPEN = 'OP'
    CLOSED = 'CL'

    STATUS_CHOICES = [
        (CLOSED, 'Closed'),
        (OPEN, 'Open'),
    ]

    name = models.CharField(max_length=255)
    description = models.CharField(max_length=1024)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=OPEN)
    seniority = models.ForeignKey('seniority', on_delete=models.PROTECT, related_name='positions')

    def __str__(self):
        return self.name


class Seniority(models.Model):
    seniority = models.CharField(max_length=2)

    def __str__(self):
        return self.seniority

    
class Subarea(models.Model):
    subarea = models.CharField(max_length=255)
    area = models.ForeignKey('area', on_delete=models.SET_NULL,
                             null=True, related_name='subareas')

    def __str__(self):
        return self.subarea
    
class Area(models.Model):
    area = models.CharField(max_length=255)

    def __str__(self):
        return self.area

viz/models.py
from django.db import models

# Create your models here.

viz/forms.py
from django import forms

def select_form_factory(field_names):
    CHOICES = (False, True)
    fields = {name: forms.TypedChoiceField(choices=CHOICES, coerce=bool,
                                           required=False, initial=False,
                                           widget=forms.CheckboxInput, )
              for name in field_names}
    fields['CHOCIES'] = CHOICES
    return type('ScoreForm', (forms.Form,), fields)

class ListFilterForm(forms.Form):
    candidate = forms.CharField(required=False)

base/views.py
from django.shortcuts import redirect, render 
from django.contrib.auth.decorators import login_required
from django.urls import reverse

viz/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from interview.models import Interview

from .stats import StatCalculator
from .forms import select_form_factory, ListFilterForm

import json
import logging

logger = logging.getLogger(__name__)

def detail(request, interview_id):
    interview = get_object_or_404(Interview, pk=interview_id)
    question_scores = interview.question_scores
    calculator = StatCalculator()
    area_results = [[area.area, result]
                    for area, result in calculator.calculate_area_avg(question_scores).items()]
    seniority_results = [[seniority.seniority, result]
                    for seniority, result in calculator.calculate_seniority_avg(question_scores).items()]
    subarea_results = [[subarea.subarea, result]
                       for subarea, result in calculator.calculate_subarea_avg(question_scores).items()]
    
    return render(request, 'viz/detail.html', {
        'interview': interview,
        'area_results': json.dumps(area_results),
        'seniority_results': json.dumps(seniority_results),
        'subarea_results': json.dumps(subarea_results),
    })

def filter_factory(param, value):
    if param == 'from_date':
        return {'date__gte': value}
    if param == 'to_date':
        return {'date__lte': value}
    if param == 'candidate':
        return {'candidate__name__regex': f'.*{value.lower()}.*'}
    else:
        return {}

def list(request):
    queryset = Interview.objects
    for key, value in request.GET.items():
        if value:
            filter = filter_factory(key, value)
            if filter:
                queryset = queryset.filter(**filter)
    interviews = queryset.all()
    form_fields = [f'interview_{interview.id}' for interview in interviews]
    Form = select_form_factory(form_fields)
    form = Form()
    data = [(interview, form[field]) for interview, field in zip(interviews, form_fields)]

    filter_init = {'candidate': request.GET.get('candidate', '')}
    filter_form = ListFilterForm(initial=filter_init)

    return render(request, 'viz/list.html', {
        'data': data,
        'filter_form': filter_form
    })

def compare(request):
    pks = [int(param.replace('interview_', ''))
           for param in request.GET if 'interview_' in param]
    interviews = Interview.objects.filter(pk__in=pks).all()
    calc = StatCalculator()
    seniority_per_interview = {interview: calc.calculate_seniority_avg(interview.question_scores)
                             for interview in interviews}
    area_per_interview = {interview: calc.calculate_area_avg(interview.question_scores)
                             for interview in interviews}
    subarea_per_interview = {interview: calc.calculate_subarea_avg(interview.question_scores)
                             for interview in interviews}
    subarea_data = bucketize(interviews, subarea_per_interview, 'Subarea')
    seniority_data = bucketize(interviews, seniority_per_interview, 'Seniority')
    area_data = bucketize(interviews, area_per_interview, 'Area')
    return render(request, 'viz/compare.html', {
       'subarea_data': json.dumps(subarea_data),
       'area_data': json.dumps(area_data),
       'seniority_data': json.dumps(seniority_data),
       'interviews': interviews,
   })


def json_export(request, interview_id):
    interview = get_object_or_404(Interview, pk=interview_id)
    json = interview.jsonfy()
    return HttpResponse(json)

def bucketize(interviews, results_per_interview, header):
    buckets = {bucket for result in results_per_interview.values()
               for bucket in result}
    header = [header] + [interview.candidate.name for interview in interviews]
    body = []
    for bucket in buckets:
        row = [str(bucket)]
        for interview in interviews:
            try:
                row.append(results_per_interview[interview][bucket])
            except KeyError:
                row.append(0)
        body.append(row)
    return [header] + body

viz/templates/viz/base.html
{% extends "base/base.html" %}

{% block header %}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
{% load static %}
<script type="text/javascript" src="{% static "viz/charts.js" %}"></script>
{% endblock header %}

viz/templates/viz/compare.html
{% extends "viz/base.html" %}

{% block content %}

<script type="text/javascript">

  google.charts.load('current', {'packages':['corechart']});
  google.charts.setOnLoadCallback(drawSeniorities);
  google.charts.setOnLoadCallback(drawAreas);
  google.charts.setOnLoadCallback(drawSubareas);

  function drawSeniorities() {
      var data = new google.visualization.arrayToDataTable({{seniority_data | safe}});
      var chart = new google.visualization.ComboChart(document.getElementById('seniority_chart'));
      chart.draw(data, comboChartOptionFactory("Seniorities"));
  }

  function drawAreas(){
      var data = new google.visualization.arrayToDataTable({{area_data | safe}});
      var chart = new google.visualization.ComboChart(document.getElementById('area_chart'));
      chart.draw(data, comboChartOptionFactory("Area"));
  }

  function drawSubareas(){
      var data = new google.visualization.arrayToDataTable({{subarea_data | safe}});
      var chart = new google.visualization.ComboChart(document.getElementById('subarea_chart'));
      chart.draw(data, comboChartOptionFactory("Subarea"));
  }
  
</script>

<style>
  .result {
      display: flex;
      flex-direction: column;
      align-items: center;
      
  }
  .table {
      width: 50%;
  }

</style>

<center>

  <h2>Candidate Comparison</h2>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>Candidate</th>
        <th>Position</th>
        <th>Interview Result</th>
      </tr>
    </thead>

    {% for interview in interviews %}
    <tbody>
      <tr>
        <td>{{interview.id}}</td>
        <td>{{interview.candidate.name}}</td>
        <td>{{interview.position.name}}</td>
        <td>{{interview.result}}</td>
      </tr>
    </tbody>
    {% endfor %}
  </table>

</center>

<div class="result">
  <div id="seniority_chart"></div>
  <div id="area_chart"></div>
  <div id="subarea_chart"></div>
</div>

{% endblock %}

viz/templates/viz/detail.html
{% extends "base/base.html" %}

{% block content %}

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
  let area_results = {{area_results | safe}}
  let subarea_results = {{subarea_results | safe}}
  let seniority_results = {{seniority_results | safe}}


  google.charts.load('current', {'packages':['corechart', 'table']});
  google.charts.setOnLoadCallback(drawSeniority);
  google.charts.setOnLoadCallback(drawArea);
  google.charts.setOnLoadCallback(drawSubarea);

  function columnOptionFactory() {
      return {
          width: 400,
          height: 240,
          vAxis: {
              minValue: 0,
              maxValue: 10,
          }
      };
  }

  function drawSeniority() {
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Seniority');
      data.addColumn('number', 'Score');
      data.addRows(seniority_results)


      var chart = new google.visualization.ColumnChart(document.getElementById('seniority_chart'));
      chart.draw(data, columnOptionFactory());

      var table = new google.visualization.Table(document.getElementById('seniority_table'));
      table.draw(data);
  }

  function drawArea() {
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Area');
      data.addColumn('number', 'Score');
      data.addRows(area_results)

      var options = {
          width: 400,
          height: 240,
          title: 'Area average',
      };

      var chart = new google.visualization.ColumnChart(document.getElementById('area_chart'));
      chart.draw(data, columnOptionFactory());


      var table = new google.visualization.Table(document.getElementById('area_table'));
      table.draw(data);
  }

  function drawSubarea() {
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Subarea');
      data.addColumn('number', 'Score');
      data.addRows(subarea_results)

      var options = {
          width: 400,
          height: 240,
          title: 'Subarea average',
      };

      var chart = new google.visualization.ColumnChart(document.getElementById('subarea_chart'));
      chart.draw(data, columnOptionFactory());
      var table = new google.visualization.Table(document.getElementById('subarea_table'));
      table.draw(data);
  }

</script>

<style>
  .result {
      display: flex;
      flex-direction: column;
      align-items: center;

  }
</style>

<div>
	<button type="button" class="btn btn-link">
		<a href="{% url "viz:json" interview.id %}">View Json</a>
	</button>
	<button type="button" class="btn btn-link">
		<!-- Could make a django filter to generate the json file name></-->
		<a href="{% url "viz:json" interview.id %}" download="{{interview.candidate.name}}-{{interview.date.date}}.json">Download Json</a>
	</button>
</div>

<div class="d-flex justify-content-between align-items-center" style="margin: 0px 120px 0px">
  <div>
  <h1>{{interview.candidate.name}}</h1>
  <span class="text-secondary">Position:</span> {{interview.position.name}}<br>
  <span class="text-secondary">Interviewer:</span> {{interview.interviewer}}<br>
  <span class="text-secondary">Date:</span> {{interview.date.date}}
  </div>

  <div class="border rounded-circle d-flex justify-content-center align-items-center" style="text-align: center; vertical-align: middle; height: 70px; width: 70px; background-color: #f7f7f7">
  <h1>
    <span id="result" class="">{{interview.result}}</span>
  </h1>
  </div>

</div>

<center>
  <div class="d-flex justify-content-around">

    <div class="result">
      <div id="area_chart"></div>
      <div id="area_table"></div>
    </div>


    <div class="result">
      <div id="subarea_chart"></div>
      <div id="subarea_table"></div>
    </div>


    <div class="result">
      <div id="seniority_chart"></div>
      <div id="seniority_table"></div>
    </div>

  </div>

</center>

<div class="d-flex justify-content-between align-items-center" style="margin: 0px 120px 0px">

  <div>
  <span class="text-secondary">Comments:</span><br>
  {{interview.comments}}
  </div>
</div>

<script type="text/javascript">
  {
      let elem = document.getElementById("result");
      let result = Number(elem.innerText);
      elem.innerText = result.toFixed(1);
      let resultClass = ""
      if (result < 5)
          resultClass = "text-danger";
    else if
          (5 <= result && result < 7) resultClass = "text-warning";
      else
          resultClass = "text-success";
      elem.classList = [resultClass];
  }
</script>
{% endblock %}

viz/templates/viz/list.html
{% extends "base/base.html" %}

{% block content %}

<!-- Datepicker -->
<script type="text/javascript">
  let clickHandler = form_id => {
      let name = `id_interview_${form_id}`;
      let element = document.getElementById(name);
      element.checked = !element.checked;
  }
</script>

<form method="get">
 {{filter_form}}
 <input type="submit" value="Filter">
</form>

<form method="get" action="{% url 'viz:compare' %}">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">#</th>
        <th scope="col">Candidate</th>
        <th scope="col">Position</th>
        <th scope="col">Result</th>
        <th scope="col">Date</th>
        <th scope="col">View</th>
      </tr>
    </thead>
    <tbody>
      {% for interview, field in data %}
      <tr onClick="clickHandler({{interview.id}})">
        <Td>{{field}}</td>
        <td>{{interview.id}}</td>
        <td>{{interview.candidate}}</td>
        <td>{{interview.position}}</td>
        <td>{{interview.result}}</td>
        <td>{{interview.date.date}}</td>
        <td><a href={% url 'viz:detail' interview.id %}>View</a></td>
      </tr>
      {% endfor %}
    </tbody>

    <input type="submit" value="Compare">
</form>
</table>

{% endblock %}