app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls import include, path


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('interview/', include('interview.urls')),
    path('', include('viz.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

base/urls.py
from django.urls import include, path

app_name = 'base'
urlpatterns = [
]

interview/urls.py
from django.urls import include, path

from .views import setup, evaluation, review, conclusion, observations, template_upload

app_name = 'interview'
urlpatterns = [
    path('', setup, name='setup'),
    path('evaluation', evaluation, name='evaluation'),
    path('review', review, name='review'),
    path('conclusion', conclusion, name='conclusion'),
    path('observations', observations, name='observations'),
    path('template', template_upload, name='template_upload'),
]

viz/urls.py
from django.urls import include, path

from .views import detail, list, compare, json_export

app_name = 'viz'
urlpatterns = [
    path('', list, name='list'),
    path('<int:interview_id>', detail, name='detail'),
    path('<int:interview_id>/json', json_export, name='json'),
    path('compare', compare, name='compare'),
]

base/models.py
from django.db import models

from django.contrib.auth import get_user_model


class Candidate(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Position(models.Model):
    OPEN = 'OP'
    CLOSED = 'CL'

    STATUS_CHOICES = [
        (CLOSED, 'Closed'),
        (OPEN, 'Open'),
    ]

    name = models.CharField(max_length=255)
    description = models.CharField(max_length=1024)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=OPEN)
    seniority = models.ForeignKey('seniority', on_delete=models.PROTECT, related_name='positions')

    def __str__(self):
        return self.name


class Seniority(models.Model):
    seniority = models.CharField(max_length=2)

    def __str__(self):
        return self.seniority

    
class Subarea(models.Model):
    subarea = models.CharField(max_length=255)
    area = models.ForeignKey('area', on_delete=models.SET_NULL,
                             null=True, related_name='subareas')

    def __str__(self):
        return self.subarea
    
class Area(models.Model):
    area = models.CharField(max_length=255)

    def __str__(self):
        return self.area

base/views.py
from django.shortcuts import redirect, render 
from django.contrib.auth.decorators import login_required
from django.urls import reverse

base/templates/base/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Interivew</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
      #content {
          margin: 25px 100px 20px
      }
    </style>
    {% block header %}
    {% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" href={% url "interview:setup" %}>Create Interview</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href={% url "viz:list" %}>Dashboard</a>
          </li>
          <li class="nav-item">
		  <a class="nav-link active" href="{% url "interview:template_upload" %}">Upload Template</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/admin">Admin</a>
          </li>
        </ul>
      </div>
    </nav>

    <div id="content">
      {% block content %}
      {% endblock %}
    </div>

    {% block footer %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

base/templates/base/login.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post" action="{% url 'login' %}">
  {% csrf_token %}
  <table>
    <tr>
      <td> {{ form.username.label_tag }} </td>
      <td> {{ form.username }} </td>
    </tr>
    <tr>
      <td> {{ form.password.label_tag }} </td>
      <td> {{ form.password }} </td>
    </tr>
    <input type="submit" value="login">
    <input type="hidden" name="next" value="{{ next }}">
  </table>
  
</form>

{% endblock %}